#==============================================================================
# Auto Generated Code for HardSigmodUdoPackage
#==============================================================================

# define relevant directories
SRC_DIR := ./

# define library name and corresponding directory
export LIB_DIR := ../../../libs/$(TARGET)
library := $(LIB_DIR)/libUdoHardSigmodUdoPackageReg.so

# define target architecture if not previously defined, default is x86
ifndef TARGET_AARCH_VARS
TARGET_AARCH_VARS:= -march=x86-64
endif

# set snpe_udo_root if it was defined in the config
ifndef SNPE_UDO_ROOT
SNPE_UDO_ROOT := /home/zli/snpe/snpe-2.10.0.4541/share/SnpeUdo
endif

# specify package paths, should be able to override via command line?
UDO_PACKAGE_ROOT =/home/zli/snpe/snpe-2.10.0.4541/udo/HardSigmodUdoPackage

include ../../../common.mk